# Generated by Django 5.1.3 on 2025-08-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_lang_user_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tg_id',
        ),
    ]
