# Generated by Django 5.1.3 on 2025-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_lang_remove_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('en', 'English'), ('ru', 'Russian')], default='uz', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
