# Generated by Django 5.1.3 on 2025-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'BannerModel',
                'verbose_name_plural': 'BannerModels',
                'db_table': 'banner',
            },
        ),
    ]
