# Generated by Django 5.1.3 on 2025-07-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorymodel_title_ru_categorymodel_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.categorymodel', verbose_name='Kategoriya'),
        ),
    ]
