# Generated by Django 5.1.3 on 2025-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cateogry/', verbose_name='Rasm'),
        ),
    ]
