# Generated by Django 5.1.3 on 2025-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kichik Sarlavha'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
    ]
