# Generated by Django 5.1.3 on 2025-07-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bannermodel_subtitle_bannermodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kichik Sarlavha'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kichik Sarlavha'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
    ]
