# Generated by Django 5.1.3 on 2025-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ordermodel_orderitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_type',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], default='click', max_length=30, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon'),
        ),
    ]
