# Generated by Django 5.1.3 on 2025-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ordermodel_first_name_ordermodel_lat_ordermodel_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
