# Generated by Django 5.1.3 on 2025-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bannermodel_description_bannermodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='type',
            field=models.CharField(choices=[('home', 'Bosh sahifa'), ('about', 'Biz haqimizda'), ('products', 'Mahsulotlar'), ('category', 'Kategoriyalar'), ('contact', 'Aloqa')], default='home', max_length=200),
        ),
    ]
