# Generated by Django 5.1.3 on 2025-07-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bannermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='type',
            field=models.CharField(choices=[('home', 'Bosh sahifa'), ('about', 'Biz haqimizda'), ('products', 'Mahsulotlar'), ('category', 'Kategoriyalar'), ('contact', 'Aloqa')], default='home', max_length=200, verbose_name='Sahifa'),
        ),
    ]
