# Generated by Django 5.1.3 on 2025-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contactmodel_messagesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
    ]
