# Generated by Django 5.1.3 on 2025-07-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contactmodel_address_ru_contactmodel_address_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesmodel',
            old_name='first_anme',
            new_name='first_name',
        ),
    ]
