# Generated by Django 5.1.3 on 2025-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ordermodel_payment_status_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pay_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
