# Generated by Django 5.1.3 on 2025-08-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ordermodel_pay_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bot Mahsulotidagi rasm'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bot Mahsulotidagi rasm'),
        ),
    ]
