# Generated by Django 5.1.3 on 2025-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_productmodel_image_id_productmodel_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
