# Generated by Django 5.1.3 on 2025-08-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_ordermodel_lat_alter_ordermodel_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bot Mahsulotidagi Video'),
        ),
        migrations.CreateModel(
            name='ProductimageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.productmodel', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'ProductimageModel',
                'verbose_name_plural': 'ProductimageModels',
                'db_table': 'productImage',
            },
        ),
    ]
