# Generated by Django 5.1.3 on 2025-08-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_ordermodel_addess_ordermodel_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='addess',
            new_name='address',
        ),
    ]
