# Generated by Django 5.1.3 on 2025-08-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_commentmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand/')),
            ],
            options={
                'verbose_name': 'BrandModel',
                'verbose_name_plural': 'BrandModels',
                'db_table': 'brand',
            },
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.productmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='api.brandmodel', verbose_name='Brend'),
        ),
    ]
