# Generated by Django 5.1.3 on 2025-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_brandmodel_remove_categorymodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cateogry/', verbose_name='Rasm'),
        ),
    ]
