# Generated by Django 5.1.3 on 2025-08-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_brandmodel_image_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_type',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqt pul')], default='click', max_length=30, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='api.brandmodel', verbose_name='Kategorya'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.categorymodel', verbose_name='Brend'),
        ),
    ]
