# Generated by Django 5.1.3 on 2025-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_brandmodel_title_ru_brandmodel_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_type',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqt pul')], default='cash', max_length=30, verbose_name="To'lov turi"),
        ),
    ]
